import 'dotenv/config'
import { v4 as uuidv4 } from 'uuid'
import { RiskDecision } from '@merchant-risk-agent/shared'
import { saveDynamoReview } from './lib/dynamo'

const DEMO_MERCHANTS: RiskDecision[] = [
  // === FRAUD CASES (5) ===
  {
    id: uuidv4(),
    merchantInput: {
      merchantName: 'AppleMart Electronics',
      upiId: 'applemrt.9@ybl',
      businessType: 'Electronics retailer',
      accountAgeDays: 14,
      avgTransactionINR: 45000,
      websiteUrl: 'applemart-india.in',
      location: 'Hyderabad, Telangana',
      transactionVolume30d: 623,
      phoneNumber: '9430112233',
      gstNumber: '',
    },
    riskScore: 92,
    riskLevel: 'high',
    recommendedAction: 'reject',
    confidenceScore: 88,
    confidenceReason: 'Multiple corroborating fraud signals across UPI pattern, transaction velocity, and web presence checks',
    policiesTriggered: [
      'P1: New account high velocity - 14-day-old account with 623 transactions far exceeds 500/month threshold',
      'P2: UPI ID typosquat - "applemrt.9@ybl" impersonates Apple brand with misspelling and numeric suffix',
      'P3: High-ticket electronics new account - Electronics retailer under 60 days with Rs 45,000 avg transaction',
      'P4: No verifiable web presence - Domain applemart-india.in registered recently with no SSL or Google indexing',
    ],
    policiesPassed: ['P5: Location inconsistency', 'P6: Missing GST for high-volume business'],
    toolSignals: {
      domainAgeDays: 10,
      hasSSL: false,
      googleIndexedPages: 0,
      publicComplaints: 4,
      webSearchSummary: 'Multiple consumer forum posts warning about AppleMart collecting payment but not delivering electronics. Pattern matches Bajaj Electronics chargeback gang.',
      upiTyposquatMatch: true,
      typosquatConfidence: 0.91,
      linkedScamVPAs: 2,
      gstFormatValid: false,
      gstStateMatch: false,
      gstActiveStatus: false,
    },
    reasoning: 'AppleMart Electronics is a high-risk fraudulent merchant matching the Bajaj Electronics chargeback gang pattern. The 14-day-old account processes 623 transactions/month — well above the P1 threshold. UPI VPA "applemrt.9@ybl" is a clear Apple brand typosquat with 91% confidence. As an electronics retailer with Rs 45,000 avg transactions on a new account, it triggers P3. Domain is 10 days old with no SSL or indexing. No GST registration despite high-volume operations.',
    reviewedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    reviewDurationMs: 2847,
  },
  {
    id: uuidv4(),
    merchantInput: {
      merchantName: 'iStore Gujarat',
      upiId: 'istoreguj.x4@paytm',
      businessType: 'Mobile phones and accessories',
      accountAgeDays: 9,
      avgTransactionINR: 72000,
      websiteUrl: 'istoregujarat.in',
      location: 'Ahmedabad, Gujarat',
      transactionVolume30d: 412,
      phoneNumber: '9429887766',
      gstNumber: '24ZZZZZ9999Z1ZZ',
    },
    riskScore: 89,
    riskLevel: 'high',
    recommendedAction: 'reject',
    confidenceScore: 88,
    confidenceReason: 'Multiple corroborating fraud signals across UPI pattern, transaction velocity, and web presence checks',
    policiesTriggered: [
      'P1: New account high velocity - 9-day-old account with 412 transactions in 30 days',
      'P2: UPI ID typosquat - "istoreguj.x4@paytm" uses numeric suffix .x4 pattern common in scam VPAs',
      'P3: High-ticket electronics new account - Mobile phone merchant 9 days old with Rs 72,000 avg transaction',
      'P6: Missing GST for high-volume business - GSTIN "24ZZZZZ9999Z1ZZ" fails format validation',
    ],
    policiesPassed: ['P4: No verifiable web presence', 'P5: Location inconsistency'],
    toolSignals: {
      domainAgeDays: 15,
      hasSSL: true,
      googleIndexedPages: 2,
      publicComplaints: 3,
      webSearchSummary: 'Reports of fake iPhone sales via UPI in Gujarat. Pattern matches Sanand arrest case where fraudsters showed fake payment screenshots.',
      upiTyposquatMatch: true,
      typosquatConfidence: 0.82,
      linkedScamVPAs: 1,
      gstFormatValid: false,
      gstStateMatch: true,
      gstActiveStatus: false,
    },
    reasoning: 'iStore Gujarat matches the fake iPhone shop pattern from the Sanand 2024 arrest. The 9-day-old account handles Rs 72,000 avg transactions — extremely high for a new mobile shop. UPI VPA uses suspicious numeric suffix. The provided GSTIN fails format validation, indicating a fabricated registration number. 3 fraud complaints found online about non-delivery of mobile phones.',
    reviewedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    reviewDurationMs: 3102,
  },
  {
    id: uuidv4(),
    merchantInput: {
      merchantName: 'WealthGrow Investments',
      upiId: 'wealthgrow.99@ybl',
      businessType: 'Investment and financial services',
      accountAgeDays: 6,
      avgTransactionINR: 50000,
      websiteUrl: 'wealthgrow-india.com',
      location: 'Kolkata, West Bengal',
      transactionVolume30d: 891,
      phoneNumber: '9831445566',
      gstNumber: '',
    },
    riskScore: 96,
    riskLevel: 'high',
    recommendedAction: 'reject',
    confidenceScore: 88,
    confidenceReason: 'Multiple corroborating fraud signals across UPI pattern, transaction velocity, and web presence checks',
    policiesTriggered: [
      'P1: New account high velocity - 6-day-old account with 891 transactions is extreme burst activity',
      'P2: UPI ID typosquat - "wealthgrow.99@ybl" uses .99 numeric suffix pattern associated with scam VPAs',
      'P4: No verifiable web presence - Domain wealthgrow-india.com registered 4 days ago, no SSL, zero indexed pages',
      'P6: Missing GST for high-volume business - Monthly GMV exceeds Rs 4.4 crore with no GST registration',
    ],
    policiesPassed: ['P3: High-ticket electronics new account', 'P5: Location inconsistency'],
    toolSignals: {
      domainAgeDays: 4,
      hasSSL: false,
      googleIndexedPages: 0,
      publicComplaints: 8,
      webSearchSummary: 'Multiple reports of WealthGrow collecting investment deposits via UPI and disappearing. RBI unregistered investment scheme alert. Website taken down after complaints.',
      upiTyposquatMatch: true,
      typosquatConfidence: 0.85,
      linkedScamVPAs: 5,
      gstFormatValid: false,
      gstStateMatch: false,
      gstActiveStatus: false,
    },
    reasoning: 'WealthGrow Investments is almost certainly a fraudulent investment scheme. The 6-day-old account processes 891 transactions with Rs 50,000 avg — textbook burst fraud. Domain is 4 days old, hosted outside India, with zero web presence. 8 fraud complaints found including RBI unregistered scheme alerts. VPA uses known scam numeric suffix pattern. 5 linked scam VPAs detected. No GST despite Rs 4.4 crore estimated monthly GMV.',
    reviewedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    reviewDurationMs: 2654,
  },
  {
    id: uuidv4(),
    merchantInput: {
      merchantName: 'FlipDeals Online',
      upiId: 'flipdeals.in7@okaxis',
      businessType: 'Online retail marketplace',
      accountAgeDays: 11,
      avgTransactionINR: 8500,
      websiteUrl: 'flipdeals-india.in',
      location: 'Delhi',
      transactionVolume30d: 1240,
      phoneNumber: '9810334455',
      gstNumber: '',
    },
    riskScore: 91,
    riskLevel: 'high',
    recommendedAction: 'reject',
    confidenceScore: 88,
    confidenceReason: 'Multiple corroborating fraud signals across UPI pattern, transaction velocity, and web presence checks',
    policiesTriggered: [
      'P1: New account high velocity - 11-day-old account with 1240 transactions is extreme velocity',
      'P2: UPI ID typosquat - "flipdeals.in7@okaxis" impersonates Flipkart brand with misspelling and numeric suffix',
      'P4: No verifiable web presence - Domain flipdeals-india.in registered 7 days ago with no SSL',
      'P6: Missing GST for high-volume business - Monthly GMV exceeds Rs 1 crore with no GST registration',
    ],
    policiesPassed: ['P3: High-ticket electronics new account', 'P5: Location inconsistency'],
    toolSignals: {
      domainAgeDays: 7,
      hasSSL: false,
      googleIndexedPages: 0,
      publicComplaints: 6,
      webSearchSummary: 'CERT-In advisory warns about fake e-commerce sites mimicking Flipkart during festive season. FlipDeals matches this pattern exactly. Multiple complaints about collected payments with no delivery.',
      upiTyposquatMatch: true,
      typosquatConfidence: 0.88,
      linkedScamVPAs: 3,
      gstFormatValid: false,
      gstStateMatch: false,
      gstActiveStatus: false,
    },
    reasoning: 'FlipDeals Online is a fake e-commerce site impersonating Flipkart — matching the CERT-In Diwali 2023 advisory pattern. VPA "flipdeals.in7" is a clear brand impersonation with 88% typosquat confidence. The 11-day-old account processes 1,240 transactions/month at Rs 8,500 avg. Domain is 7 days old with zero web presence. 6 complaints found about payment collection without delivery. No GST despite over Rs 1 crore estimated monthly GMV.',
    reviewedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    reviewDurationMs: 3245,
  },
  {
    id: uuidv4(),
    merchantInput: {
      merchantName: 'Mumbai Electronics Hub',
      upiId: 'mumbaielectronics@ybl',
      businessType: 'Electronics wholesale',
      accountAgeDays: 22,
      avgTransactionINR: 28000,
      websiteUrl: 'mumbai-electronics-hub.in',
      location: 'Mumbai, Maharashtra',
      transactionVolume30d: 567,
      phoneNumber: '9829334455',
      gstNumber: '08BBBBB1234B1ZZ',
    },
    riskScore: 85,
    riskLevel: 'high',
    recommendedAction: 'reject',
    confidenceScore: 88,
    confidenceReason: 'Multiple corroborating fraud signals across UPI pattern, transaction velocity, and web presence checks',
    policiesTriggered: [
      'P1: New account high velocity - 22-day-old account with 567 transactions exceeds 500/month threshold',
      'P3: High-ticket electronics new account - Electronics wholesaler under 60 days with Rs 28,000 avg transaction',
      'P5: Location inconsistency - Phone prefix 9829 maps to Rajasthan, GST state 08 is Rajasthan, but claims Mumbai',
      'P6: Missing GST for high-volume business - GSTIN state code 08 (Rajasthan) does not match stated Mumbai location',
    ],
    policiesPassed: ['P2: UPI ID typosquat', 'P4: No verifiable web presence'],
    toolSignals: {
      domainAgeDays: 18,
      hasSSL: true,
      googleIndexedPages: 1,
      publicComplaints: 2,
      webSearchSummary: 'Sparse online presence. Two complaints about delayed electronics delivery. Address verification shows no physical store at stated Mumbai location.',
      upiTyposquatMatch: false,
      typosquatConfidence: 0.12,
      linkedScamVPAs: 0,
      gstFormatValid: true,
      gstStateMatch: false,
      gstActiveStatus: false,
    },
    reasoning: 'Mumbai Electronics Hub shows a clear cross-state fraud pattern matching the Bajaj Electronics gang. Claims to operate in Mumbai but phone prefix 9829 maps to Rajasthan, GSTIN state code 08 is Rajasthan, and IP geolocation also shows Rajasthan. The 22-day-old account processes 567 high-value electronics transactions. GST registration is for Rajasthan, not Maharashtra — clear location deception to build buyer trust.',
    reviewedAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    reviewDurationMs: 3890,
  },

  // === EDGE CASES (3) ===
  {
    id: uuidv4(),
    merchantInput: {
      merchantName: 'Zap Couriers Mumbai',
      upiId: 'zapcouriers@okicici',
      businessType: 'Courier and logistics',
      accountAgeDays: 25,
      avgTransactionINR: 450,
      websiteUrl: 'zapcouriers.in',
      location: 'Mumbai, Maharashtra',
      transactionVolume30d: 680,
      phoneNumber: '9820556677',
      gstNumber: '27CCCCC5678C1ZZ',
    },
    riskScore: 48,
    riskLevel: 'medium',
    recommendedAction: 'review',
    confidenceScore: 62,
    confidenceReason: 'Partial risk signals present but insufficient evidence to reject outright',
    policiesTriggered: [
      'P1: New account high velocity - 25-day-old account with 680 transactions exceeds 500/month threshold',
    ],
    policiesPassed: [
      'P2: UPI ID typosquat',
      'P3: High-ticket electronics new account',
      'P4: No verifiable web presence',
      'P5: Location inconsistency',
      'P6: Missing GST for high-volume business',
    ],
    toolSignals: {
      domainAgeDays: 90,
      hasSSL: true,
      googleIndexedPages: 15,
      publicComplaints: 0,
      webSearchSummary: 'No fraud complaints. Found listed on local logistics directories. Some positive customer reviews on Google Maps.',
      upiTyposquatMatch: false,
      typosquatConfidence: 0.03,
      linkedScamVPAs: 0,
      gstFormatValid: true,
      gstStateMatch: true,
      gstActiveStatus: true,
    },
    reasoning: 'Zap Couriers Mumbai is a borderline case. The 25-day-old account exceeds the P1 velocity threshold with 680 transactions, but courier services naturally have high daily volumes at low ticket sizes (Rs 450). Domain is 90 days old with SSL and 15 indexed pages. Clean UPI VPA, valid GST matching Maharashtra, consistent location signals. No fraud complaints found. Recommend manual review — likely legitimate startup with fast early growth.',
    reviewedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    reviewDurationMs: 3567,
  },
  {
    id: uuidv4(),
    merchantInput: {
      merchantName: 'Pune Hardware Traders',
      upiId: 'punehardware@okhdfc',
      businessType: 'Hardware and construction supplies',
      accountAgeDays: 180,
      avgTransactionINR: 12000,
      websiteUrl: 'punehardwaretraders.com',
      location: 'Pune, Maharashtra',
      transactionVolume30d: 210,
      phoneNumber: '9822667788',
      gstNumber: '',
    },
    riskScore: 42,
    riskLevel: 'medium',
    recommendedAction: 'review',
    confidenceScore: 62,
    confidenceReason: 'Partial risk signals present but insufficient evidence to reject outright',
    policiesTriggered: [
      'P6: Missing GST for high-volume business - Monthly GMV Rs 25.2 lakh with no GST registration',
    ],
    policiesPassed: [
      'P1: New account high velocity',
      'P2: UPI ID typosquat',
      'P3: High-ticket electronics new account',
      'P4: No verifiable web presence',
      'P5: Location inconsistency',
    ],
    toolSignals: {
      domainAgeDays: 220,
      hasSSL: true,
      googleIndexedPages: 35,
      publicComplaints: 0,
      webSearchSummary: 'No fraud complaints. Listed on IndiaMART as hardware supplier. Some Google Maps reviews mentioning reliable service.',
      upiTyposquatMatch: false,
      typosquatConfidence: 0.01,
      linkedScamVPAs: 0,
      gstFormatValid: false,
      gstStateMatch: false,
      gstActiveStatus: false,
    },
    reasoning: 'Pune Hardware Traders appears legitimate but has a compliance gap. The 180-day-old account has normal transaction patterns for a hardware business. Domain is well-established with SSL and 35 indexed pages. Clean UPI VPA, consistent Maharashtra location signals. However, monthly GMV of Rs 25.2 lakh legally requires GST registration. This is likely a compliance oversight rather than fraud — recommend review to request GST documentation.',
    reviewedAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    reviewDurationMs: 2890,
  },

  // === LEGITIMATE MERCHANTS (3) ===
  {
    id: uuidv4(),
    merchantInput: {
      merchantName: 'Sharma Kirana Store',
      upiId: 'sharmakirana@okicici',
      businessType: 'Grocery and provisions',
      accountAgeDays: 730,
      avgTransactionINR: 380,
      websiteUrl: '',
      location: 'Jaipur, Rajasthan',
      transactionVolume30d: 290,
      phoneNumber: '9829112233',
      gstNumber: '',
    },
    riskScore: 8,
    riskLevel: 'low',
    recommendedAction: 'approve',
    confidenceScore: 78,
    confidenceReason: 'No significant fraud indicators detected across policy checks',
    policiesTriggered: [],
    policiesPassed: [
      'P1: New account high velocity',
      'P2: UPI ID typosquat',
      'P3: High-ticket electronics new account',
      'P4: No verifiable web presence',
      'P5: Location inconsistency',
      'P6: Missing GST for high-volume business',
    ],
    toolSignals: {
      publicComplaints: 0,
      webSearchSummary: 'No fraud complaints. Found on Google Maps as a local grocery shop in Jaipur with 4.3 star rating.',
      upiTyposquatMatch: false,
      typosquatConfidence: 0.01,
      linkedScamVPAs: 0,
    },
    reasoning: 'Sharma Kirana Store is a clearly legitimate local grocery business. The 2-year-old account has typical kirana store patterns — moderate frequency (290/month) at very low ticket size (Rs 380). No website is normal for a neighborhood grocery. Clean UPI VPA with no suspicious patterns. Phone prefix matches Rajasthan. GMV well below GST threshold. Found on Google Maps with positive ratings. All 6 policies passed.',
    reviewedAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    reviewDurationMs: 2234,
  },
  {
    id: uuidv4(),
    merchantInput: {
      merchantName: 'Ananya Boutique',
      upiId: 'ananyaboutique@okaxis',
      businessType: "Women's clothing and accessories",
      accountAgeDays: 420,
      avgTransactionINR: 1800,
      websiteUrl: 'ananyaboutique.in',
      location: 'Bengaluru, Karnataka',
      transactionVolume30d: 145,
      phoneNumber: '9845223344',
      gstNumber: '29AAAAA1234A1ZZ',
    },
    riskScore: 6,
    riskLevel: 'low',
    recommendedAction: 'approve',
    confidenceScore: 78,
    confidenceReason: 'No significant fraud indicators detected across policy checks',
    policiesTriggered: [],
    policiesPassed: [
      'P1: New account high velocity',
      'P2: UPI ID typosquat',
      'P3: High-ticket electronics new account',
      'P4: No verifiable web presence',
      'P5: Location inconsistency',
      'P6: Missing GST for high-volume business',
    ],
    toolSignals: {
      domainAgeDays: 480,
      hasSSL: true,
      googleIndexedPages: 95,
      publicComplaints: 0,
      webSearchSummary: 'No complaints. Positive reviews on Google Maps and Instagram. Featured in Bengaluru fashion blog.',
      upiTyposquatMatch: false,
      typosquatConfidence: 0.02,
      linkedScamVPAs: 0,
      gstFormatValid: true,
      gstStateMatch: true,
      gstActiveStatus: true,
    },
    reasoning: 'Ananya Boutique is a well-established legitimate business. The 420-day-old account has modest, consistent transaction patterns (145/month at Rs 1,800). Domain is 480 days old with SSL and 95 indexed pages. Clean UPI VPA. Phone prefix matches Karnataka. GSTIN state code 29 matches Karnataka and registration is active. Positive reviews found on Google Maps and Instagram. All 6 policies passed.',
    reviewedAt: new Date(Date.now() - 60 * 60 * 60 * 1000).toISOString(),
    reviewDurationMs: 1987,
  },
  {
    id: uuidv4(),
    merchantInput: {
      merchantName: 'Spice Garden Restaurant',
      upiId: 'spicegarden@upi',
      businessType: 'Restaurant and food service',
      accountAgeDays: 1095,
      avgTransactionINR: 650,
      websiteUrl: 'spicegardenrestaurant.com',
      location: 'Chennai, Tamil Nadu',
      transactionVolume30d: 890,
      phoneNumber: '9840334455',
      gstNumber: '33EEEEE7890E1ZZ',
    },
    riskScore: 5,
    riskLevel: 'low',
    recommendedAction: 'approve',
    confidenceScore: 78,
    confidenceReason: 'No significant fraud indicators detected across policy checks',
    policiesTriggered: [],
    policiesPassed: [
      'P1: New account high velocity',
      'P2: UPI ID typosquat',
      'P3: High-ticket electronics new account',
      'P4: No verifiable web presence',
      'P5: Location inconsistency',
      'P6: Missing GST for high-volume business',
    ],
    toolSignals: {
      domainAgeDays: 1200,
      hasSSL: true,
      googleIndexedPages: 150,
      publicComplaints: 0,
      webSearchSummary: 'No complaints. Well-reviewed restaurant on Zomato and Google Maps. Featured in Chennai food guides. 4.4 star rating with 500+ reviews.',
      upiTyposquatMatch: false,
      typosquatConfidence: 0.01,
      linkedScamVPAs: 0,
      gstFormatValid: true,
      gstStateMatch: true,
      gstActiveStatus: true,
    },
    reasoning: 'Spice Garden Restaurant is a well-established legitimate business with the lowest risk score. The 3-year-old account has high but expected transaction volume for a popular restaurant (890/month at Rs 650). Domain is over 3 years old with SSL and 150 indexed pages. Clean UPI VPA. Phone prefix matches Tamil Nadu. GSTIN state code 33 matches Tamil Nadu and is active. Excellent online reputation with 500+ Zomato reviews. All 6 policies passed.',
    reviewedAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    reviewDurationMs: 2456,
  },
]

async function seed() {
  console.log('Seeding 10 demo merchants into DynamoDB...\n')

  for (const merchant of DEMO_MERCHANTS) {
    const name = merchant.merchantInput.merchantName
    const action = merchant.recommendedAction.toUpperCase()
    const score = merchant.riskScore
    try {
      await saveDynamoReview(merchant)
      console.log(`  [${action}] ${name} (score: ${score}) — saved`)
    } catch (err) {
      console.error(`  FAILED: ${name} —`, err)
    }
  }

  console.log('\nDone! 10 demo merchants seeded.')
}

seed().catch(console.error)
