export interface TestCase {
  id: string
  description: string
  source: string
  expectedVerdict: 'approve' | 'review' | 'reject'
  expectedPolicies: string[]
  input: {
    merchantName: string
    upiId: string
    businessType: string
    accountAgeDays: number
    avgTransactionINR: number
    websiteUrl?: string
    location: string
    transactionVolume30d: number
    gstNumber?: string
  }
}

export const TEST_CASES: TestCase[] = [
  // FRAUD CASES (TC01-TC08) — expected: reject
  {
    id: 'TC01',
    description: 'Delhi Instagram iPhone scam — delhi_apple_store0',
    source: 'thestatesman.com — Delhi Police arrest Oct 2025',
    expectedVerdict: 'reject',
    expectedPolicies: ['P1', 'P2', 'P3'],
    input: {
      merchantName: 'AppleMart Electronics',
      upiId: 'applemrt.9@ybl',
      businessType: 'Mobile phones and accessories',
      accountAgeDays: 14,
      avgTransactionINR: 45000,
      websiteUrl: 'https://applemart-india.in',
      location: 'Delhi',
      transactionVolume30d: 623,
      gstNumber: '',
    },
  },
  {
    id: 'TC02',
    description: 'Kolkata investment scheme — website vanished',
    source: 'aseemjuneja.in — documented 2024',
    expectedVerdict: 'reject',
    expectedPolicies: ['P1', 'P2', 'P4'],
    input: {
      merchantName: 'WealthGrow Investments',
      upiId: 'wealthgrow.99@ybl',
      businessType: 'Investment and financial services',
      accountAgeDays: 6,
      avgTransactionINR: 50000,
      websiteUrl: 'https://wealthgrow-india.com',
      location: 'Kolkata, West Bengal',
      transactionVolume30d: 891,
      gstNumber: '',
    },
  },
  {
    id: 'TC03',
    description: 'Fake Diwali e-commerce — cloned Flipkart domain',
    source: 'CERT-In advisory 2023 + CloudSEK Diwali 2024 report',
    expectedVerdict: 'reject',
    expectedPolicies: ['P1', 'P4'],
    input: {
      merchantName: 'FlipDeals Online',
      upiId: 'flipdeals.in7@okaxis',
      businessType: 'Online retail marketplace',
      accountAgeDays: 11,
      avgTransactionINR: 8500,
      websiteUrl: 'https://flipdeals-india.in',
      location: 'Delhi',
      transactionVolume30d: 1240,
      gstNumber: '',
    },
  },
  {
    id: 'TC04',
    description: 'Thane fake GST racket — ₹75 crore fraud',
    source: 'the420.in — Thane Cyber Police Nov 2024',
    expectedVerdict: 'reject',
    expectedPolicies: ['P1', 'P5'],
    input: {
      merchantName: 'Mumbai Trade Solutions',
      upiId: 'mumbaittrade.9@ybl',
      businessType: 'Wholesale trading',
      accountAgeDays: 18,
      avgTransactionINR: 85000,
      websiteUrl: 'https://mumbaitrade-solutions.in',
      location: 'Mumbai, Maharashtra',
      transactionVolume30d: 743,
      gstNumber: '27ZZZZZ9999Z9ZZ',
    },
  },
  {
    id: 'TC05',
    description: 'Delhi stolen PAN used for fake GST — ₹70 crore',
    source: 'a2ztaxcorp.net — Oct 2025',
    expectedVerdict: 'reject',
    expectedPolicies: ['P1', 'P5'],
    input: {
      merchantName: 'Narela Export House',
      upiId: 'narelaexports@ybl',
      businessType: 'Export and import trading',
      accountAgeDays: 9,
      avgTransactionINR: 120000,
      location: 'Delhi',
      transactionVolume30d: 412,
      gstNumber: '07AAAAA0000A0ZZ',
    },
  },
  {
    id: 'TC06',
    description: 'Nationwide fake GST network — 23 states forged docs',
    source: 'the420.in — fake GST racket Nov 2025',
    expectedVerdict: 'reject',
    expectedPolicies: ['P1', 'P5'],
    input: {
      merchantName: 'Lucknow Scrap Traders',
      upiId: 'lucknowscrap.x4@paytm',
      businessType: 'Scrap metal trading',
      accountAgeDays: 15,
      avgTransactionINR: 95000,
      location: 'Lucknow, Uttar Pradesh',
      transactionVolume30d: 287,
      gstNumber: '09BBBBB1111B1ZZ',
    },
  },
  {
    id: 'TC07',
    description: 'PM Cares Fund VPA spoof — disaster relief impersonation',
    source: 'Wibmo UPI fraud trends report',
    expectedVerdict: 'reject',
    expectedPolicies: ['P1', 'P2'],
    input: {
      merchantName: 'PM Cares Relief Fund',
      upiId: 'pmcares.relief9@ybl',
      businessType: 'Charitable organization',
      accountAgeDays: 3,
      avgTransactionINR: 2500,
      websiteUrl: 'https://pmcares-relief.in',
      location: 'Delhi',
      transactionVolume30d: 1890,
      gstNumber: '',
    },
  },
  {
    id: 'TC08',
    description: 'Faridabad burst fraud — ₹4.43 crore stolen via merchant wallets',
    source: 'the420.in — Faridabad cyber scam Dec 2025',
    expectedVerdict: 'reject',
    expectedPolicies: ['P1', 'P2'],
    input: {
      merchantName: 'FastPay Solutions',
      upiId: 'fastpay.now9@paytm',
      businessType: 'Payment services',
      accountAgeDays: 7,
      avgTransactionINR: 3200,
      location: 'Faridabad, Haryana',
      transactionVolume30d: 1456,
      gstNumber: '',
    },
  },

  // EDGE CASES (TC09-TC12) — expected: review
  {
    id: 'TC09',
    description: 'New legitimate courier startup — high early volume',
    source: 'Reconstructed — legitimate new business pattern',
    expectedVerdict: 'review',
    expectedPolicies: [],
    input: {
      merchantName: 'Zap Couriers Mumbai',
      upiId: 'zapcouriers@okicici',
      businessType: 'Courier and logistics',
      accountAgeDays: 25,
      avgTransactionINR: 450,
      websiteUrl: 'https://zapcouriers.in',
      location: 'Mumbai, Maharashtra',
      transactionVolume30d: 680,
      gstNumber: '27CCCCC5678C1ZZ',
    },
  },
  {
    id: 'TC10',
    description: 'Established hardware trader — missing GST despite high volume',
    source: 'Reconstructed — informal economy merchant pattern',
    expectedVerdict: 'review',
    expectedPolicies: ['P5'],
    input: {
      merchantName: 'Pune Hardware Traders',
      upiId: 'punehardware@okhdfc',
      businessType: 'Hardware and construction supplies',
      accountAgeDays: 180,
      avgTransactionINR: 12000,
      websiteUrl: 'https://punehardwaretraders.com',
      location: 'Pune, Maharashtra',
      transactionVolume30d: 210,
      gstNumber: '',
    },
  },
  {
    id: 'TC11',
    description: 'New electronics shop — 6 months old, real GSTIN, should pass P3',
    source: 'Reconstructed — legitimate electronics retailer',
    expectedVerdict: 'approve',
    expectedPolicies: [],
    input: {
      merchantName: 'Chennai Mobile World',
      upiId: 'chennaimobiles@okaxis',
      businessType: 'Mobile phones and electronics',
      accountAgeDays: 185,
      avgTransactionINR: 18000,
      websiteUrl: 'https://chennaимobileworld.in',
      location: 'Chennai, Tamil Nadu',
      transactionVolume30d: 145,
      gstNumber: '33DDDDD4321D1ZZ',
    },
  },
  {
    id: 'TC12',
    description: 'New clothing seller — low ticket, no website, should pass all',
    source: 'Reconstructed — informal online seller pattern',
    expectedVerdict: 'approve',
    expectedPolicies: [],
    input: {
      merchantName: 'Priya Fashion Hub',
      upiId: 'priyafashion@upi',
      businessType: 'Women clothing and accessories',
      accountAgeDays: 45,
      avgTransactionINR: 850,
      location: 'Jaipur, Rajasthan',
      transactionVolume30d: 120,
      gstNumber: '',
    },
  },

  // LEGITIMATE MERCHANTS (TC13-TC15) — expected: approve
  {
    id: 'TC13',
    description: 'Established grocery store — 3 years, low volume',
    source: 'Reconstructed — standard kirana store profile',
    expectedVerdict: 'approve',
    expectedPolicies: [],
    input: {
      merchantName: 'Sharma Kirana Store',
      upiId: 'sharmakirana@okicici',
      businessType: 'Grocery and provisions',
      accountAgeDays: 730,
      avgTransactionINR: 380,
      location: 'Jaipur, Rajasthan',
      transactionVolume30d: 290,
      gstNumber: '',
    },
  },
  {
    id: 'TC14',
    description: 'Registered fashion boutique — valid GSTIN, established',
    source: 'Reconstructed — registered small business',
    expectedVerdict: 'approve',
    expectedPolicies: [],
    input: {
      merchantName: 'Ananya Boutique',
      upiId: 'ananyaboutique@okaxis',
      businessType: 'Womens clothing and accessories',
      accountAgeDays: 420,
      avgTransactionINR: 1800,
      websiteUrl: 'https://ananyaboutique.in',
      location: 'Bengaluru, Karnataka',
      transactionVolume30d: 145,
      gstNumber: '29AAAAA1234A1ZZ',
    },
  },
  {
    id: 'TC15',
    description: 'Established restaurant — 3 years, food business, valid GST',
    source: 'Reconstructed — standard restaurant profile',
    expectedVerdict: 'approve',
    expectedPolicies: [],
    input: {
      merchantName: 'Spice Garden Restaurant',
      upiId: 'spicegarden@upi',
      businessType: 'Restaurant and food service',
      accountAgeDays: 1095,
      avgTransactionINR: 650,
      websiteUrl: 'https://spicegardenrestaurant.com',
      location: 'Chennai, Tamil Nadu',
      transactionVolume30d: 890,
      gstNumber: '33EEEEE7890E1ZZ',
    },
  },
]
